public enum PoolObjectType
{
	PlayerBullet,
	FireShockWave,
	FireWalk,
	FireAmon,
	ChronosBullet,
	LongEnemyBullet,
	Coin,
	MiddleHeal,
	HighHeal,
	AmonMeleeBullet,
	PopUpDamage,
	PlayerBulletHit,
	ChronosBulletHit,
	LongEnemyBulletHit,
	AmonMeleeBulletHit,
	PlayerDashMesh,
	AmonBullet,
	AmonBulletParticle
}